### ISSUE TITLE
CUFFT library not found

### ISSUE THREAD

**Issue by kambysese** [lebedov/scikit-cuda#157]
OS X noob and have never encountered this one on LINUX machines with similar software configurations. Running skcuda version 0.5.1 in ANACONDA env with CUDA toolkit 7.5 & pycuda installed on OS X 10.11.2.  

`from skcuda.cuda import fft`

 returns an returns OSError: cufft library not found, also affecting other python programs using CUDA e.g., [mne.cuda](https://github.com/mne-tools/mne-python/issues/2744) @Eric89GXL

**Comment by lebedov** [comment]
Did you try to [set DYLD_LIBRARY_PATH](http://scikit-cuda.readthedocs.org/en/latest/install.html#building-and-installation) to the CUDA library path?

**Comment by kambysese** [comment]
Any idea exactly what that argument should be? I tried `export DYLD_LIBRARY_PATH="/usr/local/cuda/bin"` or "/usr/local/cuda/lib" or "/Developer/NVIDIA/CUDA-7.5/lib" all with same OS error. And why is this behavior so different from installation(s) on LINUX?

**Comment by lebedov** [comment]
DYLD_LIBRARY_PATH should be set to whatever directory contains the shared library file libcufft.dylib; my understanding is that this should be either /Developer/NVIDIA/CUDA-7.5/lib or /usr/local/cuda/lib on recent releases of MacOSX. Were you able to get PyCUDA running on your system? If not, you may wish to check on the pycuda mailing list to see if anyone else has encountered problems with MacOSX 10.11 - the problem may be related to why Python can't find other CUDA shared libraries. Unfortunately, I don't have access to a MacOSX system on which to test scikit-cuda.

On Linux, the path to the CUDA libraries is typically added to the ld.so cache by the CUDA toolkit installer so that the libraries can be found by all executables without explicitly setting an environment variable. MacOSX doesn't use ld.so for loading libraries, however, and it seems that updating DYLD_LIBRARY_PATH is necessary to inform its library loader (dyld) where certain libraries are located.

**Comment by DusanNikolov** [comment]
Maybe it is the same problem that I had with cuBLAS library not being found. The clash between 32bit python installation and the 64bit CUDA. You can perhaps check that first, just to make sure.

Because, as of CUDA Toolkit v6.5, NVIDIA stopped providing 32bit cuFFT and cuBLAS libraries, and that goes for many other libraries from the CUDA Toolkit.

**Comment by lebedov** [comment]
As Anaconda for MacOSX is 64-bit, I don't believe that this is the same issue as #156.

**Comment by kambysese** [comment]
@lebedov Unless you have some other explicit check in mind PyCUDA appears to be running fine as per simple [examples](http://documen.tician.de/pycuda/) 
@DusanNikolov I am running 64-bit version of Anaconda

**Comment by lebedov** [comment]
Yes - simple checks were what I was alluding to; since PyCUDA contains a shared library that is dynamically linked against one of the CUDA shared libraries, I wanted to confirm that it runs properly. Still not sure why Python can't find the other libraries, though.

A possible workaround for the problem that you can try is replacing the string ``libcufft.dylib`` on [line 18](https://github.com/lebedov/scikit-cuda/blob/master/skcuda/cufft.py#L18) in cufft.py with the full path to the libcufft.dylib library file.

**Comment by kambysese** [comment]
No - this is not a feasible wa, and considering I seem to be only person on the face of earth with this problem I may have installed your program wrong (although skcuda.__version__ returns 0.5.1). FYI editing line 18 in cufft.py means editing line 16 in cudart.py, line 13 in cudadrv.py, line 31 in cublas.py so on... Something else is wrong here

**Comment by lebedov** [comment]
Yes, but it might be worth trying the workaround with cufft.py only just to confirm that the problem is related to the library search path.

**Comment by kambysese** [comment]
I verified that CUDA is compiled and running properly on my system. Further modifications of skcuda files leads to a `KeyError` in `utils.find_lib_path` at [line 159](https://github.com/lebedov/scikit-cuda/blob/master/skcuda/utils.py#L159). For some reason `os.environ['DYLD_LIBRARY_PATH']` does not exist although it is set in ~/.bash_profile i.e., 

`export DYLD_LIBRARY_PATH="/Developer/NVIDIA/CUDA-7.5/lib:"` 

Substituting `PATH` for `DYLD_LIBRARY_PATH` returns `None` as expected and presumably modifies $PATH at line 16.1

My bet is it's a ANACONDA issue overlooked on the SKCUDA end see [here](https://github.com/conda/conda/issues/1169) and [here](https://github.com/conda/conda-build/pull/312)

**Comment by lebedov** [comment]
Can you please try the [fix_osx_find_lib_path](https://github.com/lebedov/scikit-cuda/tree/fix_osx_find_lib_path) branch? I tried updating the code to not depend on DYLD_LIBRARY_PATH exclusively.

**Comment by kambysese** [comment]
Same result. Here is trace from `test_fft`

>Error
Traceback (most recent call last):
 File "/Users/ktavabi/anaconda/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/ktavabi/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/ktavabi/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/ktavabi/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/ktavabi/Projects/scikit-cuda/tests/test_fft.py", line 16, in <module>
    import skcuda.fft as fft
  File "/Users/ktavabi/Projects/scikit-cuda/skcuda/fft.py", line 13, in <module>
    from . import cufft
  File "/Users/ktavabi/Projects/scikit-cuda/skcuda/cufft.py", line 43, in <module>
    raise OSError('cufft library not found')
OSError: cufft library not found


>ERROR: Failure: OSError (cufft library not found)
Traceback (most recent call last):
  File "/Users/ktavabi/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/ktavabi/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/ktavabi/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/ktavabi/Projects/scikit-cuda/tests/test_fft.py", line 16, in <module>
    import skcuda.fft as fft
  File "/Users/ktavabi/Projects/scikit-cuda/skcuda/fft.py", line 13, in <module>
    from . import cufft
  File "/Users/ktavabi/Projects/scikit-cuda/skcuda/cufft.py", line 43, in <module>
    raise OSError('cufft library not found')
OSError: cufft library not found
Ran 1 test in 0.001s
FAILED (errors=1)
Process finished with exit code 1

**Comment by kambysese** [comment]
@lebedov I am going to close this. Feel free to re-open if necessary.

**Comment by lebedov** [comment]
Sure - sorry I don't have further insight re the problem. Can't debug MacOSX issues myself because I don't have a Mac.
