### ISSUE TITLE
skcuda.linalg.svd with cusolver fail

### ISSUE THREAD

**Issue by ntuloser** [lebedov/scikit-cuda#169]
I run into problem while trying to make svd decomposition with cusolver, the code is given as below

```
from __future__ import print_function

import pycuda.autoinit
import pycuda.gpuarray as gpuarray
import pycuda.driver as drv
import numpy as np

import skcuda.linalg as culinalg
import skcuda.misc as cumisc
culinalg.init()


rows = 20
cols = 10
a = np.random.random((rows, cols)).astype(np.float32)  
a_gpu= gpuarray.to_gpu(a)
u_gpu,s_gpu,vh_gpu = culinalg.svd(a_gpu, 'A', 'A','cusolver')

```

The error message gives,
```

Traceback (most recent call last):
  File "diag.py", line 21, in <module>
    u_gpu,s_gpu,vh_gpu = culinalg.svd(a_gpu, 'A', 'A','cusolver')
  File "/home/stud/ga63zuh/.local/lib/python2.7/site-packages/skcuda/linalg.py", line 246, in svd
    int(devInfo.gpudata))
  File "/home/stud/ga63zuh/.local/lib/python2.7/site-packages/skcuda/cusolver.py", line 633, in cusolverDnDgesvd
    cusolverCheckStatus(status)
  File "/home/stud/ga63zuh/.local/lib/python2.7/site-packages/skcuda/cusolver.py", line 134, in cusolverCheckStatus
    raise CUSOLVER_EXCEPTIONS[status]
skcuda.cusolver.CUSOLVER_STATUS_INVALID_VALUE
```

I also encounter some problem while using cusolver from skcuda directly. I am not sure it is my problem or the problem of the package.   
I am also in doubt that the "rwork" variable is created correctly. Since in [Nvidia's page ](http://docs.nvidia.com/cuda/cusolver/index.html#cuds-lt-t-gt-gesvd), the rwork is marked as on host instead of device.

**Comment by lebedov** [comment]
CUSOLVER's svd routines only can decompose matrices with at least as many rows as columns; since the Python interface effectively computes the transpose of the specified matrix, this implies that the specified matrix must have at least as many columns as rows - I added an exception to the svd routine to catch this scenario.

The current online information regarding the rwork parameter seems somewhat incomplete - the C header implies that it is an array, but the docs imply that it should be an integer (like Lwork). In any event, I updated the code to use host memory for rwork instead of device memory.
