### ISSUE TITLE
CUDA 8 on Ubuntu 16 and cudadrv.py

### ISSUE THREAD

**Issue by bwkchee** [lebedov/scikit-cuda#174]
I'm running scikit-cuda version 0.5.1 on an Ubuntu 16 system with CUDA 8.0RC and Nvidia drivers 367.35 with dual M6000 and dual GTX1080. 

Importing skcuda/linalg would fail because line 10 of cudadrv.py looks for 'libcuda.so' however on my system (and potentially others) libcuda is no longer named libcuda.so but there's a symlink libcuda.so.1 to the currently installed nvidia driver libcuda.   Creating a link from libcuda.so.1 or libcuda.so.367.35 to libcuda.so will allow the cudarv.py to load the cuda driver.  

Not really a bug report but maybe a feature enhancement would be using a regex/conditional block (like in the win32 section, >line 20) to find either the latest libcuda as in the case of libcuda.so.(driverversion) or finding any available libcuda.so.*

**Comment by lebedov** [comment]
How did you install CUDA 8.0RC? The libcuda.so link should have been created during installation of the driver files; I don't see anything in CUDA 8.0.27 that suggests that the link should no longer be present.

**Comment by mbeyeler** [comment]
I just ran into the same issue on Ubuntu 16.04.1 with NVIDIA driver 361.42, which I installed via `apt-get` in a virtual terminal. (I went with this driver because newer ones would crash X11.)

I agree that this is related to the driver installation, not CUDA 8.0RC. Running `locate libcuda.so` reveals that the library lives in `/usr/lib/x86_64-linux-gnu`. Perhaps this directory is not on skcuda's search path?

My workaround was to create a symbolic link to `/usr/lib/x86_64-linux-gnu/libcuda.so` from a searchable path, e.g. `/usr/local/lib`.

Let me know if there's a better way to fix this issue.

**Comment by lebedov** [comment]
@mbeyeler: `/usr/lib/x86_64-linux-gnu` should be in the library loader's search path by default on recent 64-bit Linux systems such as Ubuntu 16. Can you try running `ldconfig` as root on your system to refresh the library loader's path cache and then check if you can find `libcuda.so` in the output of `ldconfig -p`?

**Comment by mbeyeler** [comment]
@lebedov: Thanks for your prompt help. I'm happy to report that your suggestion solved the problem. 
Strange, I always reboot after driver installations, and I thought `ldconfig` would be automatically performed on startup. Perhaps not. Not sure what went wrong there...

Also, keep up the good work!

**Comment by lebedov** [comment]
@mbeyeler: great!

I'm closing this because skcuda should rely on the OS library loader to make libcuda accessible rather than try to find the libraries itself.
