### ISSUE TITLE
0.5.2 release?

### ISSUE THREAD

**Issue by sclarkson** [lebedov/scikit-cuda#224]
I couldn't find any information on a roadmap for 0.5.2. Do you have any plans for an official release?

**Comment by kelsiuss** [comment]
*bump* also would like an update on this

**Comment by alipunjani** [comment]
It would be great to know the plan for a release. 
Im a scientific software developer and many users have the latest GPUs, but the compatibility issues of 0.5.1 with CUDA 9.2 and CUDA 10 are causing trouble. I know this is already fixed in the master branch, would be great to see it go out in a release!

**Comment by lebedov** [comment]
0.5.2 released. There obviously are still unresolved bugs, but a new release was long overdue.
