### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'scikit-cuda'

### ISSUE THREAD

**Issue by slarke** [lebedov/scikit-cuda#262]
I can't run created .exe. Try compile with cx_freeze or pyinstaller. After launch .exe i get message 
```
File "fft_demo.py", line 10, in <module>
    import skcuda.fft as cu_fft
  File "C:\Python36\lib\site-packages\skcuda\__init__.py", line 10, in <module>
    from .version import __version__
  File "C:\Python36\lib\site-packages\skcuda\version.py", line 2, in <module>
    __version__ = pkg_resources.require('scikit-cuda')[0].version
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Python36\lib\site-packages\pkg_resources\__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'scikit-cuda' distribution was not found and is required by the application
``` 
When i try compile demos from pycuda, then i need use hooks, but hooks dont help in these examples

**Comment by lebedov** [comment]
See the pyinstaller [FAQ](https://github.com/pyinstaller/pyinstaller/wiki/FAQ) - pyinstaller can't handle packages that use setuptools' [pkg_resources](https://setuptools.readthedocs.io/en/latest/pkg_resources.html) unless they are packaged as eggs. I tried packaging scikit-cuda as an egg and putting it in the executable directory created by pyinstaller, but ran into pycuda import issues (presumably because pycuda also isn't properly handled by pyinstaller). You might want to try [nuitka](http://nuitka.net/).
