### ISSUE TITLE
Analog of scipy.integrate.quad not implemented

### ISSUE THREAD

**Issue by jaimecoj** [lebedov/scikit-cuda#303]
Why is there implementation for more stange functions of integration and not for quad?

**Comment by lebedov** [comment]
The integration algorithms in [QUADPACK](http://nines.cs.kuleuven.be/software/QUADPACK/) that scipy exposes are more complicated than simple numerical integration routines and hence less trivial to port to a GPU. At the time I needed a GPU-based numerical integration routine, I opted for the more simple integration techniques to save implementation time (and because they were sufficient for the functions I was integrating then).
